// This file is automatically generated. Do not modify it manually.

// IMPORTANT: Do not accidentally commit this file to your repository.
// This configuration contains sensitive information.

import { FirebaseOptions } from 'firebase/app';

export const firebaseConfig: FirebaseOptions = {
  projectId: "studio-5110869673-da0f5",
  appId: "1:1083910723777:web:6fcca3faa18560d836dc40",
  apiKey: "AIzaSyAN8YW0t-AIX4802Sa1nx2wwSnV4WDYuFc",
  authDomain: "studio-5110869673-da0f5.firebaseapp.com",
  measurementId: "",
  messagingSenderId: "1083910723777",
  storageBucket: "studio-5110869673-da0f5.appspot.com"
};
